// Flat ESLint config for the SPA.
//
// Keep the rule set deliberately conservative: this is the first lint
// pass that's ever run on the SPA, and we want `npm run lint` to be
// green on the existing tree without sweeping refactors. The TS
// project itself already enforces `strict`, `noUnusedLocals`, and
// `noUnusedParameters` (see frontend/tsconfig.app.json), so ESLint
// here is a thin layer on top focused on:
//
//   - typescript-eslint recommended (no type-checking variant — keeps
//     lint independent of `tsc -b` so it's still useful when the
//     project tree isn't fully built)
//   - react-hooks recommended (rules-of-hooks + exhaustive-deps)
//   - react-refresh (only-export-components warning for HMR sanity)
//   - eslint-config-prettier last, to disable any rules that would
//     fight Prettier's formatting decisions
//
// Stylistic rules are owned by Prettier (see .prettierrc.json),
// not ESLint.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      // Generated by `make openapi-export` from the FastAPI schema —
      // never hand-edited, no value in linting it.
      "src/api/types.gen.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        // `process` shows up only in vite.config.ts / vitest.config.ts
        // (which read env), but globals.browser doesn't carry it; add
        // it for the tooling files we lint alongside src/.
        process: "readonly",
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // Prefer the typescript-eslint variant, which understands
      // declaration merging and ambient types.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // The SPA uses `any` in a small number of places where wire
      // shapes from third-party APIs (Konva pointer events, msw
      // request bodies, jsdom XHR shims) make a tighter type more
      // noise than signal. Treat `any` as a warning, not an error,
      // so it surfaces in review without blocking lint.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    files: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        // Vitest globals are enabled in vitest.config.ts; mirror the
        // ones we actually use in tests.
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        vi: "readonly",
        // jsdom + node globals that creep into test scaffolding.
        global: "readonly",
        Buffer: "readonly",
      },
    },
    rules: {
      // Tests routinely cast around to satisfy mocks; loosen these
      // so the lint pass doesn't punish the test scaffolding.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
    },
  },
  // Must come last: turns off any stylistic ESLint rule that would
  // conflict with Prettier's formatting.
  eslintConfigPrettier,
);
